### ISSUE TITLE
Moving css files into own directory, using typography-plugin and whitelisting

### ISSUE THREAD

**Issue by gamue** [kangabru/jekyll-tailwindcss-boilerplate#5]
First of all thank you very much for creating that starter template, it's one of many that I tested and one of only a few that works well in my repo!

I have a couple of questions as I want to adopt it to my needs, would highly appreciate if you could answer them:

1. Can I move the `.css` files into an directory to have it structured? I'm thinking about created multiple css-files (e.g. for the components) and would like to keep the files inside the root at a minimum.
2. What's the reason of `"@tailwindcss/typography"` needing to be in `dependencies` instead of `devDependencies`, shouldn't it be behave the same? And is there a down side of not using the typography-plugin? Looks like your boilerplate code is the only jekyll one using it, so wondering about the reason/benefit/alternative
3. How can I add `css`-styles/files that doesn't get purged? I'm using lightbox (or similar) and in my previous `purgecss.config.js` I had `whitelistPatterns: [/mfp-.*/]` defined, does that work the same in the `tailwind.config.css`

Thanks for your answers and time in advance

**Comment by kangabru** [comment]
You're welcome and I'm glad it's working in you repo!

> Can I move the .css files into an directory to have it structured?

Yeah I actually like that idea so I just pushed an update to do that. Get the latest on master and everything will be under the `styles` folder. [Here's the commit](https://github.com/kangabru/jekyll-tailwindcss-boilerplate/commit/8dad1c8488d0ec7afe8eecaef48a0dbacd245a87) in case you wanted to see how I did it/do it yourself.

Now when you add new CSS files you have two options:
- Import them via the `index.css` file like `syntax.css` is. This will get picked up by Parcel and will bundle it along with everything into the `dist/index.css` file.
- Import a CSS file directly via Jekyll by referencing it from the `head.html` file

---

> What's the reason of "@tailwindcss/typography" needing to be in dependencies instead of devDependencies?

Yeah my bad. In this case it didn't affect anything in `dependencies` but I've just moved it to `devDependencies` to keep it clean.

---

> is there a down side of not using the typography-plugin?

It just provides some nice default styles for markdown generated elements ([like in the demo article here](https://jekyll-tailwindcss-boilerplate.netlify.app/2020/01/01/demo.html)). Without it you would have to style and whitelist any generated elements via Tailwind yourself (like headers, paragraphs etc). [More info here](https://tailwindcss.com/docs/typography-plugin).

You can use it for blog posts (via the `prose` classes) and ignore it for everything else. And if you don't need it then feel free to remove it as it adds ~18KB to the final CSS file.

---

> How can I add css-styles/files that doesn't get purged?

You can access all the PurgeCSS options via the `tailwind.config.js` as shown [in the docs here](https://tailwindcss.com/docs/optimizing-for-production#purge-css-options). There's a good [more advanced example here](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/demo/tailwind.config.js) which I found useful before.

---

Hope that helps! Have any further questions at all?

**Comment by gamue** [comment]
Again, Thank you very much!
